<?php
namespace Xlab;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-07-05 at 14:53:41.
 */
class ProductsManagerTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var ProductsManager
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new ProductsManager;

    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Xlab\ProductsManager::showProducts
     * @todo   Implement testShowProducts().
     */
    public function testShowProducts()
    {
        //Tworzymy produkty, wartości które mają być sprawdzone
        $product1 = new \Xlab\Product(1999, 'Warcraft 3');
        $product2 = new \Xlab\Product(5999, 'World of Warcraft');
        $product3 = new \Xlab\Product(6999, 'Diablo 3');

        $products = array($product1, $product2, $product3);

        //wywołujemy testowaną metodę
        $actual = $this->object->showProducts($products);

        //usuwa spacje, taby
        $actual = str_replace(["\n", "\t"], '', $actual);

        //wypisuje oczekiwany html który ma zwrócić metoda showProducts
        $expected = '<ol>'
            . '<li class="promoted">Warcraft 3 (19.99)</li>'
            . '<li>World of Warcraft (59.99)</li>'
            . '<li>Diablo 3 (69.99)</li>'
            . '</ol>';
        //ewentualnie potem możemy użyć znowu funckji str_replace dla $expected


        //wywołujemy test z wiadomością, w przypadku niepowodzenia
        $this->assertSame($expected, $actual, 'expected products not qual');
    }
}
