<?php
namespace Xlab\Service;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-07-05 at 14:53:41.
 */
class ProductsPromotionApplierTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var ProductsManager
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new ProductsPromotionApplier();

    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Xlab\ProductsManager::showProducts
     * @todo   Implement testShowProducts().
     */
    public function testSort()
    {
        //Tworzymy produkty, wartości które mają być sprawdzone
        $product1 = new \Xlab\Product(1999, 'Warcraft 3');
        $product2 = new \Xlab\Product(6999, 'World of Warcraft');

        $products = array($product1, $product2);

        //wywołujemy testowaną metodę
        $actual = $this->object->apply($products);


        //usuwa spacje, taby
        $actual = $actual[0]->getPrice();



        //wypisuje oczekiwany html który ma zwrócić metoda showProducts
        $expected = 1999;


        //wywołujemy test z wiadomością, w przypadku niepowodzenia
        $this->assertSame($expected, $actual, 'expected products not qual');
    }
}
